export interface Sector {
  id: string
  label: string
  icon: string
  subcategories: string[]
}

export const SECTORS: Sector[] = [
  {
    id: 'tecnologia',
    label: 'Tecnología e Innovación',
    icon: '💻',
    subcategories: [
      'Empresas de software',
      'Agencias de desarrollo web',
      'Agencias de marketing digital',
      'Startups tech',
      'Integradores de sistemas',
      'Empresas de ciberseguridad',
      'Consultoras IT',
      'Empresas de inteligencia artificial',
      'Empresas de análisis de datos',
      'Proveedores de servicios en la nube',
      'Empresas de e-commerce',
      'Soporte técnico y mantenimiento',
      'Empresas de telecomunicaciones',
      'Desarrollo de aplicaciones móviles',
      'Automatización y robótica',
    ],
  },
  {
    id: 'salud',
    label: 'Salud y Bienestar Médico',
    icon: '🏥',
    subcategories: [
      'Clínicas y consultorios médicos',
      'Hospitales',
      'Laboratorios clínicos',
      'Farmacias y droguerías',
      'Odontología y ortodoncia',
      'Ópticas y optometría',
      'Fisioterapia y rehabilitación',
      'Salud mental y psicología',
      'Veterinarias y clínicas animales',
      'Medicina estética',
      'Centros de diálisis',
      'Ginecología y pediatría',
      'Nutrición y dietética',
      'Cirugía plástica',
      'Homeópatas y medicina alternativa',
      'Oncología',
      'Centros geriátricos',
      'Ortopedia y traumatología',
    ],
  },
  {
    id: 'educacion',
    label: 'Educación y Formación',
    icon: '🎓',
    subcategories: [
      'Colegios privados',
      'Universidades e institutos técnicos',
      'Centros de idiomas',
      'Academias de música y arte',
      'Guarderías y jardines infantiles',
      'Centros de capacitación empresarial',
      'Tutorías y refuerzo académico',
      'Escuelas de conducción',
      'Cursos de programación',
      'Academias deportivas',
      'Colegios bilingües',
      'Plataformas de e-learning',
      'Cursos de diseño y creatividad',
      'Formación en salud y enfermería',
      'Institutos de gastronomía',
    ],
  },
  {
    id: 'servicios_profesionales',
    label: 'Servicios Profesionales',
    icon: '💼',
    subcategories: [
      'Firmas de abogados',
      'Contadores y auditores',
      'Consultoras de gestión',
      'Recursos humanos y headhunting',
      'Arquitectura y diseño de interiores',
      'Ingeniería y consultoría técnica',
      'Publicidad y relaciones públicas',
      'Fotografía y producción audiovisual',
      'Diseño gráfico y branding',
      'Notarías y registros',
      'Gestión contable y nómina',
      'Consultoras de innovación',
      'Agencias de viajes',
      'Traducciones e interpretación',
      'Consultoría ambiental',
      'Gestión de proyectos',
      'Seguridad privada',
    ],
  },
  {
    id: 'construccion',
    label: 'Construcción y Real Estate',
    icon: '🏗️',
    subcategories: [
      'Constructoras',
      'Inmobiliarias',
      'Ferreterías y materiales de construcción',
      'Acabados y decoración',
      'Plomería y fontanería',
      'Instalaciones eléctricas',
      'Aire acondicionado y refrigeración',
      'Vidriería y aluminios',
      'Paisajismo y jardinería',
      'Impermeabilización',
      'Pintura y drywall',
      'Puertas y ventanas',
      'Pisos y revestimientos',
      'Estructuras metálicas',
      'Interventoría y supervisión de obras',
      'Topografía y geotecnia',
    ],
  },
  {
    id: 'finanzas',
    label: 'Finanzas y Seguros',
    icon: '💰',
    subcategories: [
      'Bancos y cooperativas de ahorro',
      'Aseguradoras',
      'Fintech y pagos digitales',
      'Fondos de inversión',
      'Leasing y crédito',
      'Casas de cambio',
      'Fiduciarias',
      'Pensiones y cesantías',
      'Microfinanzas y microcrédito',
      'Factoring y descuento de facturas',
      'Bolsas de valores',
      'Seguros de vida',
      'Seguros de automóviles',
    ],
  },
  {
    id: 'manufactura',
    label: 'Manufactura e Industria',
    icon: '🏭',
    subcategories: [
      'Industria textil y confección',
      'Alimentos y bebidas',
      'Industria química y farmacéutica',
      'Plásticos y empaques',
      'Metalmecánica',
      'Muebles y carpintería',
      'Papel y artes gráficas',
      'Electrónica y eléctrica',
      'Calzado y marroquinería',
      'Joyería y bisutería',
      'Caucho y vulcanización',
      'Pinturas y recubrimientos',
      'Minerales y cementos',
      'Industria del cuero',
      'Autopartes y mecánica industrial',
    ],
  },
  {
    id: 'logistica',
    label: 'Logística y Transporte',
    icon: '🚚',
    subcategories: [
      'Empresas de transporte de carga',
      'Mensajería y courier',
      'Almacenes y centros logísticos',
      'Agencias de aduana',
      'Transporte de pasajeros',
      'Mudanzas y trasteos',
      'Logística de última milla',
      'Transporte refrigerado',
      'Grúas y maquinaria pesada',
      'Operadores portuarios',
      'Carga aérea',
      'Distribución de alimentos',
      'Logística farmacéutica',
    ],
  },
  {
    id: 'comercio',
    label: 'Comercio y Retail',
    icon: '🛍️',
    subcategories: [
      'Supermercados y minimercados',
      'Tiendas de ropa y moda',
      'Electrodomésticos y tecnología',
      'Librería y papelería',
      'Juguetería',
      'Deportes y actividades outdoor',
      'Hogar y decoración',
      'Concesionarios de automóviles',
      'Motos y accesorios',
      'Repuestos y talleres mecánicos',
      'Ópticas y lentes',
      'Joyerías',
      'Ferreterías retail',
      'Mascotas y accesorios',
      'Distribuidores mayoristas',
      'Venta de equipos médicos',
    ],
  },
  {
    id: 'alimentos',
    label: 'Alimentos y Hospitalidad',
    icon: '🍽️',
    subcategories: [
      'Restaurantes',
      'Cafeterías y panaderías',
      'Hoteles y hostales',
      'Catering y banquetes',
      'Bares y discotecas',
      'Pastelerías y heladerías',
      'Food trucks',
      'Distribuidoras de alimentos',
      'Plantas de producción de alimentos',
      'Fruterías y tiendas naturistas',
      'Licoreras',
      'Vinotecas',
      'Clubes sociales',
      'Centros de convenciones',
    ],
  },
  {
    id: 'energia',
    label: 'Energía y Medio Ambiente',
    icon: '⚡',
    subcategories: [
      'Energía solar fotovoltaica',
      'Energía eólica',
      'Gestión de residuos y reciclaje',
      'Consultoría ambiental',
      'Petróleo y gas',
      'Distribución de gas natural',
      'Eficiencia energética',
      'Tratamiento de aguas',
      'Ingeniería ambiental',
      'Empresas de aseo y limpieza',
      'Fumigación y control de plagas',
    ],
  },
  {
    id: 'agro',
    label: 'Agro e Industria Rural',
    icon: '🌱',
    subcategories: [
      'Cultivos y agricultura',
      'Ganadería y lácteos',
      'Acuicultura y pesca',
      'Agroindustria',
      'Proveedores agropecuarios',
      'Flores y ornamentales',
      'Café y cacao',
      'Agroquímicos y fertilizantes',
      'Maquinaria agrícola',
      'Viveros y plantas',
      'Apicultura',
      'Avicultura',
    ],
  },
  {
    id: 'medios',
    label: 'Medios y Entretenimiento',
    icon: '🎬',
    subcategories: [
      'Medios de comunicación',
      'Producción audiovisual',
      'Agencias de publicidad',
      'Entretenimiento y organización de eventos',
      'Gaming y videojuegos',
      'Música y producción musical',
      'Estaciones de radio',
      'Canales de televisión',
      'Streaming y contenido digital',
      'Fotografía comercial',
      'Agencias de influencers',
    ],
  },
  {
    id: 'bienestar',
    label: 'Bienestar y Estética',
    icon: '💆',
    subcategories: [
      'Gimnasios y crossfit',
      'Centros de yoga y pilates',
      'Peluquerías y salones de belleza',
      'Barberías',
      'Spas y centros de masajes',
      'Centros de bronceado',
      'Tatuajes y piercings',
      'Uñas y manicure',
      'Micropigmentación',
      'Centros de medicina estética',
    ],
  },
  {
    id: 'social',
    label: 'Gobierno, Social y ONG',
    icon: '🤝',
    subcategories: [
      'ONGs y fundaciones',
      'Cooperativas',
      'Gremios y asociaciones empresariales',
      'Cámaras de comercio',
      'Entidades públicas',
      'Iglesias y comunidades religiosas',
      'Sindicatos',
      'Juntas de acción comunal',
      'Cruz Roja y organizaciones humanitarias',
    ],
  },
]
